#!/usr/bin/env bash

source sparql.sh

put "$EPR" ../../data/nasty.ttl 'text/turtle' 'http://example.com/nasty.ttl'
sparql "$EPR" 'ASK { <http://example.org/> <http://example.org/> "42" . }'
sparql "$EPR" 'ASK { <http://example.org/> <http://example.org/> "42" . }'
delete "$EPR" 'http://example.com/nasty.ttl'
