#!/usr/bin/env bash

source sparql.sh

put "$EPR" ../../data/swh.xrdf '' 'http://example.org/foaf'
sparql "$EPR" 'SELECT DISTINCT ?class WHERE { [] a ?class } ORDER BY ?class'
delete "$EPR" 'http://example.org/foaf'
