#!/usr/bin/env bash

pkg-config rasqal --atleast-version=0.9.25 || exit 3

source sparql.sh

put "$EPR" ../../data/numbers.ttl 'text/turtle' 'http://example.com/numbers.ttl'

sparql "$EPR" 'SELECT ?s ?d (ROUND(?d) AS ?abs_d) WHERE { ?s <test:num> ?d . } ORDER BY ?s'

delete "$EPR" 'http://example.com/numbers.ttl'
