#!/usr/bin/env bash

source sparql.sh

put "$EPR" ../../data/nasty.ttl 'text/turtle' 'http://example.com/nasty.ttl'
sparql "$EPR" 'SELECT ?d WHERE { <test:data> <test:bcdate> ?d . FILTER(YEAR(?d) = 1969) }' | sort
sparql "$EPR" 'SELECT ?d WHERE { <test:data> <test:bcdate> ?d . FILTER(MONTH(?d) = 5.0) }' | sort
#sparql "$EPR" 'SELECT (DAY(?d) AS ?dd) WHERE { <test:data> <test:bcdate> ?d } ORDER BY ?d'
sparql "$EPR" 'SELECT (SUBSTR(?s, 1, 3) AS ?ss) WHERE { <test:data> <test:bcd> ?s. FILTER(?s = "012345678901234567890123456789012") }'
sparql "$EPR" 'SELECT (STRSTARTS(?s, "012") AS ?sw) WHERE { <test:data> <test:bcd> ?s. FILTER(?s = "012345678901234567890123456789012") }'
sparql "$EPR" 'SELECT (STRENDS(?s, "012") AS ?ew) WHERE { <test:data> <test:bcd> ?s. FILTER(?s = "012345678901234567890123456789012") }'
sparql "$EPR" 'SELECT (CONCAT("CC") AS ?co) WHERE { <test:data> <test:bcd> ?s } ORDER BY ?co'
sparql "$EPR" 'SELECT (CONCAT("BEFORE-∂-",?s, "-§-AFTER") AS ?co) WHERE { <test:data> <test:bcd> ?s } ORDER BY ?s'
delete "$EPR" 'http://example.com/nasty.ttl'
