#!/usr/bin/env bash

source sparql.sh

update "$EPR" 'INSERT DATA { GRAPH <a> { <x> <y> <z> . <a> <b> <c> . } }'
update "$EPR" 'INSERT DATA { GRAPH <a> { <a> <b> <d> . } }'
sparql "$EPR" 'SELECT DISTINCT * WHERE { ?s ?p ?o } ORDER BY ?s ?p ?o'
update "$EPR" 'INSERT { <x> <y> <w> } WHERE { <a> <b> <c> }'
update "$EPR" 'INSERT { <x> <y> ?o } WHERE { <a> <b> ?o }'
sparql "$EPR" 'SELECT DISTINCT * WHERE { GRAPH ?G { ?s ?p ?o } } ORDER BY ?s ?p ?o'
update "$EPR" 'DELETE DATA { <x> <y> <z> }'
sparql "$EPR" 'SELECT DISTINCT * WHERE { ?s ?p ?o } ORDER BY ?s ?p ?o'
sparql "$EPR" 'SELECT DISTINCT * WHERE { GRAPH ?G { ?s ?p ?o } } ORDER BY ?s ?p ?o'
update "$EPR" 'INSERT { GRAPH <c> { ?ns <p> ?s } } WHERE { ?s <b> <c> . ?s <b> ?ns }'
sparql "$EPR" 'SELECT DISTINCT * WHERE { GRAPH ?G { ?s ?p ?o } } ORDER BY ?s ?p ?o'
update "$EPR" 'DELETE { ?x ?y ?z } WHERE { ?x ?y ?z }'
