#!/usr/bin/env bash

source sparql.sh

post "$EPR" '<test:a> <test:b> <test:c> .' 'text/turtle' 'http://example.org/test1'
sparql "$EPR" 'SELECT * WHERE { ?x ?y ?z } ORDER BY ?x ?y ?z'
post "$EPR" '<test:d> <test:e> <test:f> . <test:d> <test:g> "text\nwith\tspaces" .' 'text/turtle' 'http://example.org/test1'
sparql "$EPR" 'SELECT * WHERE { ?x ?y ?z } ORDER BY ?x ?y ?z'
TEMPFILE="/tmp/test$$"
touch $TEMPFILE
put "$EPR" "$TEMPFILE" 'text/turtle' 'http://example.org/test1'
rm $TEMPFILE
sparql "$EPR" 'SELECT * WHERE { ?x ?y ?z } ORDER BY ?x ?y ?z'
delete "$EPR" 'http://example.org/test1'
