.Dd July 8, 2009
.Dt 4S-CLUSTER-CREATE 1J 4store
.Os 4store
.Sh NAME
.Nm 4s-cluster-create
.Nd Create a KB on the cluster.
.Sh SYNOPSIS
.Nm
kb-name
.sp
.Sh FILES
This command depends on the config file /etc/4s-cluster, see 4s-cluster(5).
.Sh EXAMPLES
$
.Nm
demo
.sp
Create the "demo" knowledgebase
.sp
Knowledgebases can be deleted with the
.Xr 4s-cluster-destroy 1
command.
.Sh CAVEATS
If the kb has already been created then it will be erased and recreated.
Because of this extreme care needs to be taken then using this command.
.Sh SEE ALSO
.Xr 4s-cluster-start 1 ,
.Xr 4s-cluster-stop 1 ,
.Xr 4s-cluster-destroy 1 ,
.Xr 4s-cluster-info 1
