language: c
sudo: false
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - git
      - make
      - autoconf
      - libtool
      - pkg-config
      - libncurses5-dev
      - libreadline6-dev
      - zlib1g-dev
      - uuid-dev
      - libxml2-dev
      - libglib2.0-dev
      - libraptor2-dev
      - librasqal3-dev
# install: make get-deps
before_script:
  - mkdir -p /tmp/4store
script:
  - ./autogen.sh
  - ./configure --with-storage-path=/tmp/4store --with-http-log=/tmp/4store
  - make
  - make test
