#!/usr/bin/env bash

echo "# before insert"
$TESTPATH/frontend/4s-query $CONF $1 '
SELECT ?p ?o
WHERE { <foo:a> ?p ?o }' | sort
$TESTPATH/frontend/4s-import $CONF $1 -m http://example.com/nasty.ttl $TESTPATH/../data/nasty.ttl 1>&2 > /dev/null
echo "# BCD test"
$TESTPATH/frontend/4s-query $CONF $1 '
SELECT ?p ?o
WHERE { <foo:a> ?p ?o }' | sort
$TESTPATH/frontend/4s-query $CONF $1 '
SELECT ?o WHERE { ?z <test:bcd> ?o } ORDER BY ?o'
echo "# after insert"
$TESTPATH/frontend/4s-delete-model $CONF $1 http://example.com/nasty.ttl 1>&2 > /dev/null
echo "# after delete"
$TESTPATH/frontend/4s-query $CONF $1 '
SELECT ?p ?o
WHERE { <foo:a> ?p ?o }' | sort
