#!/usr/bin/env bash

$TESTPATH/frontend/4s-query $CONF $1 'PREFIX foaf: <http://xmlns.com/foaf/0.1/> SELECT ?p ?name ?sha1 WHERE { ?x foaf:knows ?p OPTIONAL { ?p foaf:mbox_sha1sum ?sha1 ; foaf:name ?name } }' | sort
