#!/usr/bin/env bash

$TESTPATH/frontend/4s-query $CONF $1 '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?first ?second
WHERE { ?first <http://xmlns.com/foaf/0.1/knows> _:second . _:second foaf:name $second }' | sort
