#!/usr/bin/env bash

echo "order 1";
$TESTPATH/frontend/4s-query $CONF $1 '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?x
WHERE {
  ?x <http://xmlns.com/foaf/0.1/mbox_sha1sum> ?s .
  ?x foaf:nick ?nick .
  FILTER( ?s = "970987f991961f2553a1bf2574166fa29befbccb" ||
          ?s = "828414515d398b42268a6c2ed879dc505369223a" ||
          ?s = "4829af19130151de1c4def299d73d33f33dee0fb")
  FILTER( ?nick = "zool" ||
          ?nick = "dajobe")
}
ORDER BY ?x
'
echo "order 2";
$TESTPATH/frontend/4s-query $CONF $1 '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?x
WHERE {
  ?x <http://xmlns.com/foaf/0.1/mbox_sha1sum> ?s .
  ?x foaf:nick ?nick .
  FILTER( ?s = "970987f991961f2553a1bf2574166fa29befbccb" ||
          ?s = "828414515d398b42268a6c2ed879dc505369223a" ||
          ?s = "4829af19130151de1c4def299d73d33f33dee0fb")
  FILTER( ?nick = "dajobe" ||
          ?nick = "zool")
}
ORDER BY ?x
'
