#!/usr/bin/env bash

# tests PREFIX, numbers in var names and single OPTIONAL triple with unbound
# results, and multiple result rows for repeated predicates

$TESTPATH/frontend/4s-query $CONF $1 -f sparql -P <<EOQ
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?p ?sha1
WHERE { ?x foaf:knows ?p OPTIONAL { ?p foaf:mbox_sha1sum ?sha1 } }
ORDER BY ?sha1
EOQ
