#!/usr/bin/env bash

# tests the case where a varaible appears in more than one column of a bind,
# used to cause vertical expansion of the table due to a missing repeat check

$TESTPATH/frontend/4s-query $CONF $1 '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT *
WHERE {
  GRAPH ?g {
    ?g <http://xmlns.com/wot/0.1/assurance> ?wot .
    ?g foaf:maker ?maker
    OPTIONAL { ?maker foaf:mbox_sha1sum ?sum }
    OPTIONAL { ?maker foaf:name ?name }
  }
}
'
