#!/usr/bin/env bash

# tests DISTINCT, Jo has two mbox_sha1sums

$TESTPATH/frontend/4s-query $CONF $1 '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?p
WHERE { ?p foaf:mbox_sha1sum ?sha1 }' | sort
