#!/usr/bin/env bash

# tests optimisation of FILTER(?x = foo || ?x = bar)

$TESTPATH/frontend/4s-query $CONF $1 'SELECT DISTINCT ?b ?c WHERE { ?a ?b ?c . FILTER(?c = "Escobar St" || ?c = "Smith St") } LIMIT 10' | sort
