#!/usr/bin/env bash

$TESTPATH/frontend/4s-query $CONF $1 '
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?a ?b ?name
WHERE { ?x <http://xmlns.com/foaf/0.1/knows> ?p . ?p foaf:name ?name }' | grep -v 'was used but is not bound' | grep -v 'was selected but is unused' | sort
