#!/usr/bin/env bash

# tests OPTIONAL with large number of NULL results

$TESTPATH/frontend/4s-query $CONF $1 '
PREFIX vocab: <http://www.census.gov/tiger/2002/vocab#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX feature: <http://www.census.gov/tiger/2002/CFCC/>
SELECT DISTINCT *
WHERE {
  ?place vocab:name ?name .
  ?place a vocab:Landmark .
  OPTIONAL {
    ?place vocab:location _:loc .
    _:loc vocab:lat ?latitude ;
          vocab:long ?longitude .
  }
}'  | sort
