#!/usr/bin/env bash

# tests that OPTIONAL blocks can be safely mixed with the basic graph pattern

$TESTPATH/frontend/4s-query $CONF $1 '
PREFIX vocab: <http://www.census.gov/tiger/2002/vocab#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?endlabel ?next
WHERE {
<http://www.census.gov/tiger/2002/tlid/125030028> vocab:end ?end.
OPTIONAL { ?end rdfs:label ?endlabel }
?end vocab:long ?endlong. ?end vocab:lat ?endlat.
OPTIONAL { _:join vocab:long ?endlong. _:join vocab:lat ?endlat. ?next vocab:start _:join. }}
'
