#!/usr/bin/env bash

# tests combinatorial explosion on the same query pattern, exercises the existienatial binding optimisation

$TESTPATH/frontend/4s-query $CONF $1 'SELECT DISTINCT ?x ?y WHERE { ?x ?y "Corral Hollow Creek" . ?a ?b "Corral Hollow Creek" }' | sort
echo '==='
$TESTPATH/frontend/4s-query $CONF $1 'SELECT DISTINCT ?a ?b WHERE { ?x ?y "Corral Hollow Creek" . ?a ?b "Corral Hollow Creek" }' | sort
