#!/usr/bin/env bash

$TESTPATH/frontend/4s-query $CONF $1 'SELECT DISTINCT ?a WHERE { { ?a <http://www.w3.org/2000/01/rdf-schema#label> "Escobar St" } UNION { ?a <http://www.w3.org/2000/01/rdf-schema#label> "No Such Avenue"} } LIMIT 100'
$TESTPATH/frontend/4s-query $CONF $1 'SELECT DISTINCT ?a WHERE { { ?a <http://www.w3.org/2000/01/rdf-schema#label> "No Such Avenue" } UNION { ?a <http://www.w3.org/2000/01/rdf-schema#label> "Escobar St"} } LIMIT 100'
