#!/usr/bin/env bash

./test-create.sh --segments 4 $1
./test-start.sh $1
echo "# empty store"
$PRECMD $TESTPATH/frontend/4s-bind $1 all FS_BIND_SUBJECT FS_BIND_OBJECT FS_BIND_BY_SUBJECT /dev/null /dev/null /dev/null /dev/null
echo "# nasty.ttl"
$PRECMD $TESTPATH/frontend/4s-import $1 -m http://example.com/nasty.ttl $TESTPATH/../data/nasty.ttl 1>&2
$PRECMD $TESTPATH/frontend/4s-bind $1 all FS_BIND_SUBJECT FS_BIND_OBJECT FS_BIND_BY_SUBJECT /dev/null /dev/null /dev/null /dev/null | sort
echo "# nasty.ttl deleted"
$PRECMD $TESTPATH/frontend/4s-delete-model $1 http://example.com/nasty.ttl 1>&2
$PRECMD $TESTPATH/frontend/4s-bind $1 all FS_BIND_SUBJECT FS_BIND_OBJECT FS_BIND_BY_SUBJECT /dev/null /dev/null /dev/null /dev/null | sort
./test-stop.sh $1
