#!/usr/bin/env bash

./test-create.sh --segments 4 $1
./test-start.sh $1
echo "# import"
$PRECMD $TESTPATH/frontend/4s-import $1 -m file:swh $TESTPATH/../data/swh.xrdf
$PRECMD $TESTPATH/frontend/4s-import $1 -m file:nasty $TESTPATH/../data/nasty.ttl
$PRECMD $TESTPATH/frontend/4s-import $1 -m file:tiger $TESTPATH/../data/tiger/TGR06001.nt
echo "# size of result"
$PRECMD $TESTPATH/frontend/4s-size $1
echo "# distinct predicates by object"
$PRECMD $TESTPATH/frontend/4s-bind $1 all FS_BIND_PREDICATE FS_BIND_DISTINCT FS_BIND_BY_OBJECT /dev/null /dev/null /dev/null /dev/null | sort | uniq
./test-stop.sh $1
