#!/usr/bin/env bash

./test-create.sh --segments 1 --model-files $1
./test-start.sh $1
echo "# file segment import"
echo "# nasty.ttl bind"
$PRECMD $TESTPATH/frontend/4s-import $1 -m file:nasty $TESTPATH/../data/nasty.ttl
wc -c /var/lib/4store/$1/0000/mlist.tbchain /var/lib/4store/$1/0000/m/* | sed 's/^[^0-9]*//g'
$PRECMD $TESTPATH/frontend/4s-bind $1 all FS_BIND_SUBJECT FS_BIND_OBJECT FS_BIND_BY_SUBJECT /dev/null /dev/null /dev/null /dev/null | sort
./test-stop.sh $1

./test-create.sh --segments 1 $1
./test-start.sh $1
echo "# tblist segment import"
echo "# nasty.ttl bind"
$PRECMD $TESTPATH/frontend/4s-import $1 -m file:nasty $TESTPATH/../data/nasty.ttl
$PRECMD $TESTPATH/frontend/4s-bind $1 all FS_BIND_SUBJECT FS_BIND_OBJECT FS_BIND_BY_SUBJECT /dev/null /dev/null /dev/null /dev/null | sort
wc -c /var/lib/4store/$1/0000/mlist.tbchain /var/lib/4store/$1/0000/m/* | sed 's/^[^0-9]*//g'
./test-stop.sh $1
