#!/usr/bin/env bash

./test-create.sh --segments 4 $1
./test-start.sh $1
echo "# nasty.ttl bind"
$PRECMD $TESTPATH/frontend/4s-import $1 $TESTPATH/../data/nasty.ttl
$PRECMD $TESTPATH/frontend/4s-bind $1 all FS_BIND_SUBJECT FS_BIND_OBJECT FS_BIND_BY_SUBJECT /dev/null /dev/null /dev/null /dev/null | sort
echo "# nasty.ttl resolve"
$PRECMD $TESTPATH/frontend/4s-resolve $1 0425B6891ADBDF72
$PRECMD $TESTPATH/frontend/4s-resolve $1 76B7550D0C84F8E5
./test-stop.sh $1
