#!/bin/bash

if [[ $1 == '--help' ]] ; then
  echo "Usage: $0 <kbname>"
  exit
fi

if [[ $1 == '--version' ]] ; then
  4s-backend --version | sed 's/4s-backend/'`basename $0`'/'
  exit
fi

if (($# == 1)) ; then
 logger -t $0 "'$*' by $USER"
 4s-ssh-all "pkill -f ^4s-backend\ $1\$ || echo No matching 4store backend"
else 
 echo "Usage: $0 <kbname>"
fi
