#!/bin/sh
if (($# == 1)) ; then
 (find /var/lib/4store/$1/ -newer /var/lib/4store/$1/backup || echo "always") |
      grep "" > /dev/null || exit 2;
 touch /var/lib/4store/$1/backup
 tar -c -P -z -f - /var/lib/4store/$1/
else
 echo "Usage: $0 <kbname>" > /dev/stderr
 exit 1;
fi
