#!/bin/bash

source vars.sh

CMD="$FS_ADMIN --config-file $FS_CONF list-nodes"

# remove IP address, since this won't be consistent
OUTPUT=`$CMD | sed -e '2,$s/[^ ]\+$//g'`
EXITSTATUS=${PIPESTATUS[0]}

echo "Exit status: $EXITSTATUS"
echo "$OUTPUT"

